### ISSUE TITLE
Proyecto agenda

### ISSUE THREAD

**Issue by Carlosh-rengifo** [cris2014971130/projectContactBlazor#2]
1. Permite adicionar dos contactos con el mismo nombre.
2. Al buscar un contacto que existe, se presenta un error (cuando existen dos contactos iguales).
3. Al verificar si existe un contacto, se presenta un error (cuando existen dos contactos iguales).
4. Al eliminar un contacto, se presenta error (cuando existen dos contactos iguales).

**Comment by cris2014971130** [comment]
Problemas solucionados
